runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /(.+\.php)$
  script: \1

- url: /
  script: website.php

- url: /web/
  script: website.php

- url: /style.css
  static_files: style.css
  upload: style.css
  
  - url: /logo.png
  static_files: logo.png
  upload: logo.png
  
  - url: /alan.jpg
  static_files: alan.jpg
  upload: alan.jpg
  
  - url: /matthew.jpg
  static_files: matthew.jpg
  upload: matthew.jpg
  
error_handlers:
  - file: whoops.php
